In [11]:
import pandas as pd
import os
import datetime as dt

In [12]:
#create mplscrime dataframe
MPLS_Crime = os.path.join("Crime_Data.csv")
crime_df=pd.read_csv(MPLS_Crime)

In [13]:
crime_df

,X,Y,Type,Case_Number,Case_NumberAlt,Reported_Date,Occurred_Date,NIBRS_Crime_Against,NIBRS_Group,NIBRS_Code,...,Address,Precinct,Neighborhood,Ward,Latitude,Longitude,wgsXAnon,wgsYAnon,Crime_Count,OBJECTID
0,-93.316750,45.038778,Crime Offenses (NIBRS),19-244586,MP2019244586,2019/08/15 21:39:00+00,2019/08/15 16:00:00+00,Property,Group A,220,...,0045XX VINCENT AVE N,4.0,Victory,4.0,45.03877,-93.31675,-1.038797e+07,5.627628e+06,1,1
1,-93.293968,45.039344,Crime Offenses (NIBRS),19-122255,MP2019122255,2019/05/01 13:10:00+00,2019/05/01 10:15:00+00,Property,Group A,23F,...,0046XX DUPONT AVE N,4.0,Lind - Bohanon,4.0,45.03934,-93.29396,-1.038544e+07,5.627718e+06,1,2
2,-93.249955,44.949220,Shots Fired Calls,21-117936,NaN,2021/06/01 07:53:55+00,2021/06/01 07:53:55+00,Non NIBRS Data,Non NIBRS Data,Non NIBRS Data,...,0029XX 17TH AVE S,3.0,East Phillips,9.0,44.94921,-93.24995,-1.038054e+07,5.613531e+06,1,3
3,-93.275347,44.977582,Crime Offenses (NIBRS),20-222716,MP2020222716,2020/08/27 03:26:00+00,2020/08/26 22:54:00+00,Property,Group A,220,...,0007XX HENNEPIN AVE,1.0,Downtown West,7.0,44.97758,-93.27534,-1.038336e+07,5.617993e+06,1,4
4,-93.226094,44.935953,Crime Offenses (NIBRS),20-703897,MP2020703897,2020/07/12 11:24:00+00,2020/07/12 09:30:00+00,Property,Group A,23H,...,0032XX 37TH ST E,3.0,Standish,12.0,44.93595,-93.22609,-1.037788e+07,5.611444e+06,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200925,-93.220366,44.902660,Crime Offenses (NIBRS),22-700897,MP2022700897,2022/01/28 18:35:00+00,2022/01/22 18:30:00+00,Property,Group A,23F,...,0055XX 36TH AVE S,3.0,Minnehaha,12.0,44.90266,-93.22036,-1.037724e+07,5.606210e+06,1,200926
200926,-93.292435,45.014930,Shots Fired Calls,21-082066,NaN,2021/04/19 19:37:55+00,2021/04/19 19:37:55+00,Non NIBRS Data,Non NIBRS Data,Non NIBRS Data,...,0010XX 33RD AVE N,4.0,McKinley,4.0,45.01493,-93.29243,-1.038527e+07,5.623872e+06,1,200927
200927,-93.265202,44.950148,Crime Offenses (NIBRS),21-185969,MP2021185969,2021/08/18 02:58:00+00,2021/08/18 00:00:00+00,Property,Group A,120,...,0028XX PARK AVE,3.0,Phillips West,9.0,44.95014,-93.26520,-1.038223e+07,5.613677e+06,1,200928
200928,-93.276637,44.942251,Crime Offenses (NIBRS),19-268803,MP2019268803,2019/09/05 23:32:00+00,2019/08/12 12:30:00+00,Property,Group A,23H,...,0033XX 1ST AVE S,5.0,Lyndale,8.0,44.94225,-93.27663,-1.038351e+07,5.612435e+06,1,200929
200929,-93.293352,44.991977,Shots Fired Calls,22-163279,NaN,2022/07/18 09:54:36+00,2022/07/18 09:54:36+00,Non NIBRS Data,Non NIBRS Data,Non NIBRS Data,...,0010XX PLYMOUTH AVE N,4.0,Near - North,5.0,44.99197,-93.29335,-1.038537e+07,5.620259e+06,1,200930

In [14]:
crime_df.dtypes

X                      float64
Y                      float64
Type                    object
Case_Number             object
Case_NumberAlt          object
Reported_Date           object
Occurred_Date           object
NIBRS_Crime_Against     object
NIBRS_Group             object
NIBRS_Code              object
Offense_Category        object
Offense                 object
Problem_Initial         object
Problem_Final           object
Address                 object
Precinct               float64
Neighborhood            object
Ward                   float64
Latitude               float64
Longitude              float64
wgsXAnon               float64
wgsYAnon               float64
Crime_Count              int64
OBJECTID                 int64
dtype: object

In [15]:
now = datetime.datetime.now()
print("The time right now is ", now)

The time right now is  2022-11-13 20:15:20.202588

In [16]:
crime_df.count()

X                      200930
Y                      200930
Type                   200930
Case_Number            200930
Case_NumberAlt         171522
Reported_Date          200930
Occurred_Date          200929
NIBRS_Crime_Against    200930
NIBRS_Group            200930
NIBRS_Code             200930
Offense_Category       200930
Offense                200930
Problem_Initial        165304
Problem_Final          165304
Address                200930
Precinct               199683
Neighborhood           199619
Ward                   199513
Latitude               200930
Longitude              200930
wgsXAnon               200930
wgsYAnon               200930
Crime_Count            200930
OBJECTID               200930
dtype: int64

In [18]:
#Look for missing values
crime_df.isnull()

,X,Y,Type,Case_Number,Case_NumberAlt,Reported_Date,Occurred_Date,NIBRS_Crime_Against,NIBRS_Group,NIBRS_Code,...,Address,Precinct,Neighborhood,Ward,Latitude,Longitude,wgsXAnon,wgsYAnon,Crime_Count,OBJECTID
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200925,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
200926,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
200927,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
200928,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
200929,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [19]:
#get total of empty rows
crime_df.isnull().sum()

X                          0
Y                          0
Type                       0
Case_Number                0
Case_NumberAlt         29408
Reported_Date              0
Occurred_Date              1
NIBRS_Crime_Against        0
NIBRS_Group                0
NIBRS_Code                 0
Offense_Category           0
Offense                    0
Problem_Initial        35626
Problem_Final          35626
Address                    0
Precinct                1247
Neighborhood            1311
Ward                    1417
Latitude                   0
Longitude                  0
wgsXAnon                   0
wgsYAnon                   0
Crime_Count                0
OBJECTID                   0
dtype: int64

In [21]:
#determine if there are not any missing values
crime_df.notnull().sum()

X                      200930
Y                      200930
Type                   200930
Case_Number            200930
Case_NumberAlt         171522
Reported_Date          200930
Occurred_Date          200929
NIBRS_Crime_Against    200930
NIBRS_Group            200930
NIBRS_Code             200930
Offense_Category       200930
Offense                200930
Problem_Initial        165304
Problem_Final          165304
Address                200930
Precinct               199683
Neighborhood           199619
Ward                   199513
Latitude               200930
Longitude              200930
wgsXAnon               200930
wgsYAnon               200930
Crime_Count            200930
OBJECTID               200930
dtype: int64